# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
